### ISSUE TITLE
Odd errors with test PRs

### ISSUE THREAD

**Issue by Elisa-on-GitHub** [ubvu/open-handbook#264]
For the workshop yesterday (12 Nov) where I introduced colleagues to github functionality and the handbook, I let participants open test PRs on the README file - they were asked to add their name and favourite dessert under the heading on the bottom of the file.
However, some of them, including me, got errors that I've never seen.

## Workflow error
![handbook-workflow-approval](https://github.com/user-attachments/assets/b47cd089-fe88-439c-8b28-df8406cde468)
I don't know exactly what this refers to and whether it is fatal. This one occurred e.g. in #254, but I think also in one of the PRs that I merged yesterday (#256 and #261), although I can't see that anymore now that they're merged.

## Failed check
![handbook-failed-check](https://github.com/user-attachments/assets/7b000db0-0e07-4004-9160-0d6f0e87c593)
This error came up in PRs #258 and #260. I'm guessing that this is fatal, but I didn't try to merge on the spot because I didn't want to interrupt the highly exciting PR flow. What I don't understand is why this happens to some PRs and not others, while all of us did the same thing, because I showed them how to do this.

![handbook-email-error](https://github.com/user-attachments/assets/8948d497-e9fb-4fae-86bb-6735e9c78a96)
This is the email of the error that I received, as one of the people who got the error.

Can we investigate this? Is the issue clear like this? Do you need me to do something?

I will now close the test PRs that did not get this error.

**Comment by Elisa-on-GitHub** [comment]
P.S. Do I need to keep the names and favourite desserts in the readme for now or can this be deleted?

**Comment by chartgerink** [comment]
Thanks @Elisa-on-GitHub for the detailed report! I did some digging and I know what happened. You can remove the favorite desserts now (I'm hungry!).

## Approval 

It seems like [GitHub does not automatically run workflows on fork pull requests, for first time contributors](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks) (by default). This is a preventative measure, I think, but one I also never encountered before. So thank you for surfacing this 😊

I changed this setting to only be relevant for "first-time contributors who are new to GitHub" which should be fewer people (it is the most permissive policy I could set).

## Error

The error of the action is another aspect, which I think is also because they are forks of the repository. The error itself:

```
Error: Resource not accessible by integration
```

Which usually is a permissions issue. Checking the automation, I am not sure what it is here that would have this problem. I will update the automation to not run on forks for now.
